version: "3.7"
services:
  app:
    container_name: test_app
    build:
      context: .
      dockerfile: Dockerfile-good
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST: postgres
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:16
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/001.sql
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
volumes:
  pg_data: